version: '3.8'
services:
  db:
    container_name: "db"
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  fastapi-app:
    container_name: "backend"
    image: "fastapi:dev"
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

volumes:
  postgres_data:
